name: main

on:
  push:
    branches:
      - "master"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: [lint, test]
    uses: ./.github/workflows/release.yml
